---

- name: install mysql
  apt: 
    name: "{{item}}"
    state: present
  with_items:
    - mysql-server
    - python3-pymysql

- name: start mysql
  systemd:
    name: mysql
    state: started

- name: Create a new database for laravel
  community.mysql.mysql_db:
    name: laravel
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock